	AREA RESET, DATA, READONLY ;WRITE AN ASSEMBLY LEVEL CODE TO COPY 2 32 BIT NUMBERS FROM CODE MEMOMERY T0 DATA MEMOMERY
	EXPORT __Vectors
__Vectors
	DCD 0X10001001 ;STACK POINTER VALUE WHEN
	DCD Reset_Handler ;reset vector
	ALIGN
	AREA mycode, CODE, READONLY
	ENTRY
	EXPORT Reset_Handler
Reset_Handler
	LDR R0, =N;R0 = 0X000014?
	LDR R1, =DST
	LDR R2, [R0];R2=R0
	STR R2, [R1];OPPOSITE TO LDR
	LDR R3, [R0,#4]
	STR R3, [R1,#4]
STOP B STOP
N DCD 0X12345678,0X6A
	AREA mydata, DATA, READWRITE
DST DCD 0,2
	END