	AREA RESET, DATA, READONLY
	EXPORT __Vectors
__Vectors
	DCD 0X10001001 ;STACK POINTER VALUE WHEN
	DCD Reset_Handler ;reset vector
	ALIGN
	AREA mycode, CODE, READONLY
	ENTRY
	EXPORT Reset_Handler
Reset_Handler
	LDR R0, =N;R0 = 0X000014?
	LDR R1, =DST
	LDR R2, [R0];R2=R0
	STR R2, [R1];OPPOSITE TO LDR 
STOP B STOP
N DCD 0X12345678
	AREA mydata, DATA, READWRITE
DST DCD 0
	END